slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: chassis          
    scan_topic: /scan
    use_map_saver: true
    mode: localization
    map_file_name : /home/hetos_10/rover_ws/src/rover_bot/maps/map_serial0
    # map_start_pose : 
    map_start_at_dock : true

    debug_logging: true            
    throttle_scans: 2
    map_update_interval: 1.0
    resolution: 0.05
    min_laser_range: 0.1
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.1        
    tf_buffer_duration: 50.0     
    enable_interactive_mode: true
    use_scan_time: true          # keep true if timestamps are correct

    use_scan_matching: true
    use_scan_barycenter: true
    use_scan_smoothing: true
    minimum_travel_distance: 0.05  
    minimum_travel_heading: 0.05   
    transform_publish_period: 0.02 

    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5



    # keep loop closing, but you can temporarily disable if it causes artifacts
    do_loop_closing: false